### PR TITLE
Basic support for Hysen Heating Controller (dev type 0x4ead)

### LINKED ISSUE #130: Additional device support
Hi all,

thanks for your work so far on this.  

I want to use it with a Broadlink based heating controller ("Hysen HY02B05H", photo here: http://peter.windridge.org.uk/playing-with-cheap-iot-devices/20171120_163450.jpg ).

I can .discover() and .auth() the device.  The devtype is: 0x4ead.

(1) Has anyone started working on this device?
(2) If not, I need to capture packets from the Android app (which calls a libBLNetwork.so binary).  I tried wireshark on Ubuntu but setting promiscuous mode on my laptop doesn't seem to work.  I had considered install the Android SDK emulator to run the app on my PC but this seems like a lot of faff.  Is there any easier way?  (Sorry this question is not directly related to python-broadlink so I don't mind being told to take it elsewhere :))

My goals are: 
- read room temperature
- put control in manual mode
- change temperature

I have not tried sending the device codes from check_temperature() etc for fear of bricking it...

Peter

### PR DESCRIPTION
**Pull request by ptd006**
Contains a new device class hysen for various Broadlink-OEM WiFi thermostats made by Xiamen Hysen Control Technology Co., Ltd.  These are sold under brands including Floureon.

It now provides essentially complete support, including:
- get_temp() : get current room temperature
- set_temp(temp in degrees C) : switch to manual control and set thermostat temperature
- switch_to_auto() : switch to automatic (predefined) schedule/temperatures
- get_full_status() : get all known fields, incl. timer schedule
- set_advanced( ... ) : advanced settings
- set_time(hour,minute,second,day)
- set_schedule( ... ) : set times/temps for auto mode
- set_power : power on/off (doesn't disable WiFi) and control lock.
- set_mode : set sensor, loop mode and control mode.

Photo of device: http://peter.windridge.org.uk/playing-with-cheap-iot-devices/20171120_163450.jpg

Note that package PyCRC is used for calculating the CRC16 required in payload.   

Fixes #130

### CODE REVIEW

**Comment by ralphm2004** [comment]
Tested with
https://www.amazon.de/FLOUREON-Heizk%C3%B6rperthermostat-Heizungsthermostat-Heizungsregelung-Programmierbar/dp/B0771MPJXK
and worked.

**Comment by serjs** [comment]
Hi!

Thank you for your work! I can confirm that changes reusable for FLOUREON thermostat, i have same as @ralphm2004 mention in his comment. Looks like this solved almost all Chinese thermostat based on Broadlink OEM-T1

I also notice that you use PyCRC ([link](https://github.com/mjg59/python-broadlink/pull/138/files#diff-8651c630cb85a737f3c4c67091ea485fR628) which is new module dependency for this project. I think that we need to add this dep as setup requirements on the road to mainstream if we really need to use CRC16

@mjg59 Can you look into this?

**Comment by ptd006** [comment]
Hi @serjs,
Thanks for testing, glad it's working!

Modbus CRC16 is required.  It could  be implemented as a standalone function to avoid the extra dependency.  However,  yes overall I favour keeping it as a dep.

**Comment by ptd006** [comment]
N.b. I think part of the control code in switch_to_auto (the 0x11 in input_payload) actually controls the "loop mode" (which defines whether Saturday should follow the weekend or weekday schedule).  More specifically I think this byte should actually be:
`( (loop_mode + 1) << 4) + auto_mode
where 
```
  # auto_mode = 1 for auto (scheduled/timed) mode, 0 for manual mode
  # loop_mode refers to index in [ "12345,67", "123456,7", "1234567" ] using the Android app's notation
  # E.g. loop_mode = 0 ("12345,67") means Saturday and Sunday follow the "weekend" schedule
  # loop_mode = 2 ("1234567") means every day (including Saturday and Sunday) follows the "weekday" schedule

```

I have not tested this properly but hope to do so next week when I will also commit code to set the timer schedule.

I hadn't noticed before because I was only using "Saturday and Sunday weekend" mode (I guess that applies for most people..)

**Pull request merged**
