### PR TITLE
Added support for Luceco Smart! Downlights

### PR DESCRIPTION
**Pull request by Crashandburnds**
Thank you for creating this project, its been a great help in getting my smart home fully operational.

This PR adds support for the Luceco Smart Home Downloads.

They need to be configured as a broadlink device in fast flashing AP mode but this change makes them controllable.

### CODE REVIEW

**Review by sordfish — CHANGES_REQUESTED** [review]
I would love this to be merged as I'm adding this manually to my HA container each time.

This PR only needs line 167 of __init__.py and the version bump to work with the Luceco Smart! Downlights.

Side note: There is a batch of these with the red and green wires crossed so it's not a code bug as I first thought. My second batch from a different supplier were wired correctly.

**Comment by felipediel** [comment]
Thanks @Crashandburnds! What model are these bulbs? Something like "SLA27RGB9W81"...

**Comment by Crashandburnds** [comment]
@felipediel I'm pretty sure they are EFCF60WSMT. These are the ones I'm using (https://www.screwfix.com/p/luceco-ftype-smart-fixed-cylindrical-fire-rated-led-smart-downlight-white-6w-600lm/425kr#product_additional_details_container)

**Comment by felipediel** [comment]
Closed with https://github.com/mjg59/python-broadlink/pull/787. Thanks @Crashandburnds!

**Pull request closed without merging**
