### PR TITLE
Add support for Clas Ohlson SP4L-EU

### PR DESCRIPTION
**Pull request by Tamarinen**
This adds support for Clas Ohlson SP4L-EU, as per @skrutt 's changes in https://github.com/mjg59/python-broadlink/pull/300 . I've just ported it to the new structure, and made sure it works as advertised.

### CODE REVIEW

**Comment by skrutt** [comment]
Nice :) a new device class?

**Comment by Tamarinen** [comment]
> Nice :) a new device class?

Seems so; that's what you did, and it looked sufficiently different from the other devices to warrant that. :)

**Comment by mjg59** [comment]
Hi! Unfortunately the library has just been refactored to split the code up more cleanly - would you mind updating this so the SP4 class code goes in the appropriate file?

**Comment by Tamarinen** [comment]
Of course not.

**Comment by Tamarinen** [comment]
I'm closing this, as it is outdated.

**Pull request closed without merging**
