### PR TITLE
Add support for Broadlink SP4M-US (0x648b)

### PR DESCRIPTION
**Pull request by felipediel**
fixes https://github.com/mjg59/python-broadlink/issues/440

### CODE REVIEW

**Review by KTibow — APPROVED** [review]

**Comment by KTibow** [comment]
Any way I can use this in Home Assistant now?

**Comment by felipediel** [comment]
Yes. Follow this thread: https://github.com/home-assistant/core/issues/36624#issuecomment-705918238.

**Comment by KTibow** [comment]
Any way for you to combine all of the PRs into one?

**Comment by KTibow** [comment]
And @felipediel anything stopping you from merging this?

**Comment by felipediel** [comment]
If you only want an updated branch you can take it [here](https://github.com/felipediel/python-broadlink/tree/latest-broadlink).

**Comment by KTibow** [comment]
Getting this error:
```

**Comment by felipediel** [comment]
What is the context?

**Comment by KTibow** [comment]
```python3
>>> devices = broadlink.discover(timeout=20)
>>> devices
[<sp4: Broadlink SP4M-US (0x648b) at 192.168.1.43:80 | 24:df:a7:36:f1:4e | 25739 | Unlocked>]
>>> devices[0].set_power(True)
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    devices[0].set_power(True)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 232, in set_power
    self.set_state(pwr=state)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 262, in set_state
    return self._decode(response)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 306, in _decode
    check_error(response[0x22:0x24])
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthorizationError: [Errno -7] Control key is expired
>>> devices[0].auth()
True
>>> devices[0].set_power(True)
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    devices[0].set_power(True)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 232, in set_power
    self.set_state(pwr=state)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 262, in set_state
    return self._decode(response)
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\switch.py", line 306, in _decode
    check_error(response[0x22:0x24])
  File "C:\Users\Kende\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\broadlink\exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.DataValidationError: [Errno -6] Structure is abnormal
```

**Comment by felipediel** [comment]
I checked the official app. This device has a different communication pattern. I think it cannot be controlled with our sp4 class. Something that will help us understand this device...
```python3
import broadlink as blk
d = blk.hello("192.168.0.17")  # Example
d.auth()
print(d.decrypt(d.send_packet(0x6a, b'\xb5\xe6\xdf\xfb%\x97\xf2\x95\x10\x0f\xc7\xe9\xbe\xc9\xf2\xcb')[0x38:]))
```
What is the output?

**Comment by KTibow** [comment]
Here:
```

**Comment by felipediel** [comment]
I made a special class to support your device. Could you please help me with some tests?

**Comment by KTibow** [comment]
How do I do the tests?

**Comment by felipediel** [comment]
On you computer...
## 1. Create a venv (not mandatory)
```bash
python3 -m venv venv
source venv/bin/activate
```
## 2 . Install the library
```bash
pip3 install git+https://github.com/felipediel/python-broadlink.git@latest-broadlink --upgrade
pip3 install cryptography==2.9.2
```
## 3. Open python3
```bash
python3
```

## 4. Test controlling the device with the library
```python3
import broadlink as blk
devs = blk.discover()
devs
d = devs[0]  # Example
d.auth()
d.get_state()
d.set_power(True)
d.get_state()
d.set_power(False)
d.get_state()
```

**Comment by KTibow** [comment]
Worked! ♥ What next?

**Comment by felipediel** [comment]
Great! Now you just need to wait for these updates to be merged and released.

**Comment by KTibow** [comment]
It would work if I used the shell command function in HA as a placeholder, right?

**Comment by felipediel** [comment]
No. We need to update the Broadlink integration.

**Comment by felipediel** [comment]
@Danielhiversen @mjg59 Do you want me to group all updates related to SP4 into a single PR?

**Comment by felipediel** [comment]
@KTibow I updated the PR in Home Assistant. If you want to help test the changes, [these instructions](https://github.com/home-assistant/core/issues/36624#issuecomment-705918238) will set you up.

**Comment by KTibow** [comment]
I would, but docker needs admin rights. It works great, though!

**Comment by fkleon** [comment]
@KTibow If you can't use docker, you can alternatively install Home Assistant into a venv for testing purposes:

```
python3 -m venv venv
source venv/bin/activate

pip3 install git+https://github.com/felipediel/home-assistant.git@sp4 --upgrade
pip3 install git+https://github.com/felipediel/python-broadlink.git@latest-broadlink --upgrade
pip3 install cryptography==2.9.2

hass --open-ui
```

**Comment by mjg59** [comment]
Hey Felipe,

I merged the other SP4 commits - I assume that the correct way to merge this is to switch the existing sp4 entries to sp4l, but could you confirm that?

**Comment by felipediel** [comment]
Yes. Thank you!

**Pull request merged**
