### PR TITLE
New product ids 0x521C 0x520D 0x5211 0x648C

### PR DESCRIPTION
**Pull request by titusthefox04**
## Proposed change

Add support for the follow new device ids:
- 0x521C
- 0x520D
- 0x5211
- 0x648C

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New device
- [x] New product id (the device is already supported with a different id)
- [ ] New feature (which adds functionality to an existing device)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Additional information

- This PR fixes issue: fixes #
- This PR is related to: 
  - https://github.com/mjg59/python-broadlink/pull/710
  - https://github.com/mjg59/python-broadlink/pull/709
  - https://github.com/mjg59/python-broadlink/pull/694
  - https://github.com/mjg59/python-broadlink/pull/707
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [ ] The code has been formatted using Black.
- [ ] The code follows the [Zen of Python](https://www.python.org/dev/peps/pep-0020/).
- [x] I am creating the Pull Request against the correct branch.
- [ ] Documentation added/updated.

### CODE REVIEW

**Comment by jadson179** [comment]
Any predictions for the pull request merge ?

**Comment by unrat** [comment]
> Any predictions for the pull request merge ?

I would also appreciate a quick fix there as HA is using this repo and after every update of HA we have to manually fix this to get it working again. Is there anything i can do to speed up the process?

**Comment by kpblca** [comment]
Me also voting for enforcing of merge this pull request into next release! =)

**Comment by KingOfBaboon** [comment]
yeah, it's a known issue and known fix, please merge and release, thanks!

**Comment by mrosun** [comment]
I just bought some of the new RM4C minis and they're not supported. I came to cast my vote to please merge this, thanks! And thank you for all your work as well!

**Comment by jerrychong25** [comment]
Can someone help to approve this PR as soon as possible?

Thanks in advance!

**Comment by kpblca** [comment]
@mjg59 Mat, could you merge this PR to next release, please? 
This very useful change is stucked.

**Comment by felipediel** [comment]
Hi! This branch is internal, it will be merged as soon as I find the time to add some devices that are missing and prepare a new version, thanks!

**Comment by gtjadsonsantos** [comment]
Face this lib is very important to keep up to date, because it is used by several other applications and services, the home assistant is one of them, and very used by the people who use it.
 
I only see you currently @felipediel  moving this lib forward with the time you have, the other maintainers are not moving this project forward. I understand that after years that this lib was born, it's fucked up to continue without a financial return yet. My advice is to open doors for more people who can maintain this.

Upgrading lib versions to add new devices even if it's one, two or three is better than going months without new versions to be added.

**Comment by cfromm1911** [comment]
@felipediel Please add the missing devices.

**Pull request closed without merging**
