### PR TITLE
Add support for Broadlink SP4L-EU (0xA5D3)

### PR DESCRIPTION
**Pull request by felipediel**
From: https://github.com/home-assistant/core/issues/49596.

Thank you @dawik!

### CODE REVIEW

**Comment by dawik** [comment]
@felipediel do you think this will make its way to next months HA release?

**Comment by felipediel** [comment]
I will do my best to release it soon, but there are steps that do not depend only on me so it is impossible to determine how long it will take. If you want to add support before the release:

1. Open Home Assistant and install "SSH & Web Terminal" add-on
2. Disable Protection mode
3. Click "Terminal" on the sidebar and install the patch:
```
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git@0xa5d3 --force-reinstall --no-deps
```
4. Restart the server.

You need to reinstall the patch when you update Home Assistant.

**Comment by dawik** [comment]
> I will do my best to release it soon, but there are steps that do not depend only on me so it is impossible to determine how long it will take. If you want to add support before the release:
> 
> 1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 2. Disable Protection mode
> 3. Click "Terminal" on the sidebar and install the patch:
> 
> ```
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git@0xa5d3 --force-reinstall --no-deps
> ```
> 
> 1. Restart the server.
> 
> You need to reinstall the patch when you update Home Assistant.

Unfortunately I am bound to just use core/docker container 

But I can work around it with IFTTT until then

Thanks for your work on this!

**Comment by felipediel** [comment]
You're welcome!

**Pull request merged**
