### PR TITLE
Add a TROUBLESHOOTING doc with WiFi password notes

### LINKED ISSUE #531: RM4 Pro requires firmware update before accepting all WiFi passwords
I noticed that my RM4 Pro wouldn't connect to wifi with non-alphanumeric passwords before a firmware update. Is this common across many Broadlink products? If so, I'd be glad to update the README.

### PR DESCRIPTION
**Pull request by deviantintegral**
Resolves #531 .

### CODE REVIEW

**Comment by KTibow** [comment]
What about just adding a subheading to the readme?

**Comment by felipediel** [comment]
@deviantintegral Could we add more details, like the fw version?

@KTibow To keep things organized, we will put all the "gotchas" in this file. We can talk about how to handle exceptions like "AuthorizationError", "AuthenticationError", "StorageError" etc. The user must read this file before opening an issue.

**Comment by deviantintegral** [comment]
I'm sorry, I didn't capture the firmware version prior to upgrading.

**Comment by felipediel** [comment]
What is the devtype and current fw version?
```python3
import broadlink as blk
d = blk.hello('192.168.0.16')  # Example IP address
d.auth()
print(hex(d.devtype))
print(d.get_fwversion())
```

**Comment by deviantintegral** [comment]
```
Python 3.9.2 (default, Feb 24 2021, 13:26:09)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import broadlink as blk
>>> d = blk.hello('192.168.30.80')
>>> d.auth()
True
>>> print(hex(d.devtype))
0x6026
>>> print(d.get_fwversion())
52079
>>>
```

**Comment by felipediel** [comment]
Thank you @deviantintegral!

**Pull request merged**
