### PR TITLE
simple command line programs to use with the library 

### PR DESCRIPTION
**Pull request by ivanfmartinez**

### CODE REVIEW

**Comment by walkention** [comment]
Hey ivanfmartinez,

There is already a project you may want to check out called [BlackBeanControl](https://github.com/davorf/BlackBeanControl) that provides command line access to the python-broadlink package. It uses an INI to set up devices and store learned IR packets.

I would think that python-broadlink would want to remain a package that can be leveraged via any external wrapper like a command line interface or REST server, and be responsible for maintaining the communications API the Broadlink devices. Just my two cents though.

Thanks!

**Comment by johado** [comment]
I started to do something similar to test the package with my SP2 devices.
Despite other efforts, it might still be nice to have some basic ready to use scripts within this package if @mjg59 find such a thing acceptable and mergeable.
(I had to expose the local ip in the options for it to work om my Raspberry pi 3)

**Comment by ivanfmartinez** [comment]
@walkention  I will look at this BlackBeanControl

@johado  I agree, simple running code can be usefull for anyone who what to start using this library to test and check beforce any other integration

**Comment by mjg59** [comment]
Thank you!

**Pull request merged**
