### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by ilvi80**
Add support RM4C mini 0x520D

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New device
- [ ] New product id (the device is already supported with a different id)
- [ ] New feature (which adds functionality to an existing device)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Additional information

- This PR fixes issue: fixes #
- This PR is related to: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [ ] The code has been formatted using Black.
- [ ] The code follows the [Zen of Python](https://www.python.org/dev/peps/pep-0020/).
- [ ] I am creating the Pull Request against the correct branch.
- [ ] Documentation added/updated.

### CODE REVIEW

**Comment by ilvi80** [comment]
Add 0x520D

**Comment by bisquit2003** [comment]
Pls, we really need it.

**Comment by guieiras** [comment]
Hi!

This change is already on ```new_product_ids``` branch. @felipediel said that it will be merged as soon as he find time to prepare a new version (https://github.com/mjg59/python-broadlink/pull/715).

I understand the frustration and agree that **0x520D** support should be prioritized, because all new released Broadlink RM4c mini has this ID.

But keep in mind that this PR probably will be closed for duplication reasons.

**Comment by felipediel** [comment]
Thanks, we already have this one, I will release the new_product_ids as soon as I can.

**Pull request closed without merging**
