### PR TITLE
Add support for Broadlink RM4 pro (0x653C)

### PR DESCRIPTION
**Pull request by felipediel**
Add support for Broadlink RM4 pro (0x653C)
https://github.com/home-assistant/core/issues/42983

### CODE REVIEW

**Comment by KTibow** [comment]
You should re-sort the list sometime. Are you sure that's the location where it goes?

**Comment by felipediel** [comment]
Yes, we are sorting by class and devtype, in this order.

**Comment by lukeclx** [comment]
Seems like it's not supported again for Broadlink RM4 pro (0x653C)

**Comment by yfands** [comment]
Hey felipediel, thanks for opening, but it says Add support for Broadlink RM4 pro (0x653C)
But my device is a RM mini 3.  with that device number 0x653C
Regards Frank

**Comment by felipediel** [comment]
Are you sure? Please double check. The official app says RM4 pro.

**Comment by yfands** [comment]
Hey Felipe,

Yes iam absolutely sure I have a RM mini 3, a green one, the pro4 is all black.


oh I see the culprit..

The RM4 is 0x6539

and the RM mini 3 is 0x653c

I think my bad..... Sorry

Regards Frank



________________________________
Van: Felipe Martins Diel <notifications@github.com>
Verzonden: dinsdag 24 november 2020 22:07 uur
Aan: mjg59/python-broadlink <python-broadlink@noreply.github.com>
CC: yfands <yfands@live.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mjg59/python-broadlink] Add support for Broadlink RM4 pro (0x653C) (#472)


Are you sure? Please double check. The official app says RM4 pro.

**Comment by yfands** [comment]
Felipe,

Iam sorry I made a mess..

This is the right product and number


The RM4 is 0x6539

and the RM mini 3 is 0x6508

 Sorry

Regards Frank

________________________________
Van: Frank - <yfands@live.nl>
Verzonden: woensdag 25 november 2020 22:00 uur
Aan: mjg59/python-broadlink <reply@reply.github.com>
Onderwerp: Re: [mjg59/python-broadlink] Add support for Broadlink RM4 pro (0x653C) (#472)

Hey Felipe,

Yes iam absolutely sure I have a RM mini 3, a green one, the pro4 is all black.


oh I see the culprit..

The RM4 is 0x6539

and the RM mini 3 is 0x653c

I think my bad..... Sorry

Regards Frank



________________________________
Van: Felipe Martins Diel <notifications@github.com>
Verzonden: dinsdag 24 november 2020 22:07 uur
Aan: mjg59/python-broadlink <python-broadlink@noreply.github.com>
CC: yfands <yfands@live.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mjg59/python-broadlink] Add support for Broadlink RM4 pro (0x653C) (#472)


Are you sure? Please double check. The official app says RM4 pro.

**Comment by felipediel** [comment]
Thanks for reporting back! The PRs are open, now we just need to wait a bit for the next release.

**Comment by opep** [comment]
> 
> 
> Thanks for reporting back! The PRs are open, now we just need to wait a bit for the next release.

Do you expect that it is going to be merged with HA 1.0? It´s getting pretty near (13/12) and despite it has successful checks and no conflicts, it still didn't get merged. (I have no way to integrate my new broadlink).

**Comment by KTibow** [comment]
Steps for HA:
- Someone buys the thing
- Someone makes an issue here
- Someone figures out how to fix it
- Someone makes a PR
- PR needs to be looked at
- PR needs to be merged
- python-broadlink new release
- Update HA requirements for new release, same PR process
- New HA release

It takes a while. Hopefully the maintainers can merge soon.

**Comment by xblackedemonx** [comment]
Is it possible that it is not integrated yet? I try to add my RM4 Pro+ and it says Device not supported. thanks

**Comment by KTibow** [comment]
This PR is open, as you can see. That means that it's not added yet. It is definitely not integrated.

**Comment by opep** [comment]
> 
> 
> Is it possible that it is not integrated yet? I try to add my RM4 Pro+ and it says Unsupported device: 0x653c. thanks

Same here, We will have to wait a bit longer.

**Comment by xblackedemonx** [comment]
Ok thank you.

**Comment by oferbar** [comment]
Hi,
The same error happens for two different devices I was trying to add to HA: RM4 Pro and RM4C mini:

Logger: homeassistant.components.broadlink.config_flow
Source: components/broadlink/config_flow.py:48
Integration: Broadlink (documentation, issues)
First occurred: 2:49:35 AM (4 occurrences)
Last logged: 10:57:59 AM

Unsupported device: 0x653c. If it worked before, please open an issue at https://github.com/home-assistant/core/issues
Unsupported device: 0x6539. If it worked before, please open an issue at https://github.com/home-assistant/core/issues

**Comment by xblackedemonx** [comment]
When is this patch planned to go live?

**Comment by KTibow** [comment]
When one of the maintainers is available.

**Comment by kaskagorry** [comment]
Otro por aqui con este modelo RM4 Pro '0x653c' con el mismo problema para poder integrarlo.

En cuanto tengamos novedades sobre este asunto, soy el primero en probar

**Comment by felipediel** [comment]
Hi @kaskagorry. If you want to patch your installation before the release:
1. Open Home Assistant and install "SSH & Web Terminal" add-on
2. Disable Protection mode
3. Connect to the device via SSH and install the patch:
```
ssh USER@IPADDRESS
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
```
4. Restart the server.

**Comment by xblackedemonx** [comment]
felipediel thank you very much!

**Comment by oferbar** [comment]
> Hi @kaskagorry. If you want to patch your installation before the release:
> 
> 1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 2. Disable Protection mode
> 3. Connect to the device via SSH and install the patch:
> 
> ```
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
> ```
> 
> 1. Restart the server.

Hi, in which release is this going to be included?
Thanks!

**Comment by WarlaxZ** [comment]
patch 23 annoyingly doesnt add the '0x6539' device (RM4 Mini)

**Comment by WarlaxZ** [comment]
patch 33 however does!

**Comment by felipediel** [comment]
If you want all patches together you can use the master branch.

**Comment by lordraiden** [comment]
Will this be in the next official release?

**Comment by DangerD1024** [comment]
After update old RM pro + stopped to work for learning also, can't find device

**Comment by felipediel** [comment]
You need to re-patch after the upgrade.

**Comment by lordraiden** [comment]
> You need to re-patch after upgrading Home Assistant.

But the support for the RM4 Pro will be included by default in home assistant with the broadlink integration? Do you know when? 

I am running the latest version home assistant with docker.
It looks like there is a way to "patch" HA so I can find the device with the broadlink integration, how can I do this?

**Comment by pemoamsiiot** [comment]
> You need to re-patch after upgrading Home Assistant.

Thanks for all the repplys and the help. I just found this topic after an issue with my RM Mini 4.
Do you know in witch HA version will I be able to integrate this device? (Unsupported device: 0x6539)

Thanks again

**Comment by bakovari** [comment]
I have HA Version 2021.2.2, and latest Broadlink firmware v52079 and integration doesn't work. Same error message.

Any info when the official integration will be available with no hacking?

Thanks a lot

**Comment by xblackedemonx** [comment]
Same here. Still get an error.

**Comment by KTibow** [comment]
Just to say this again, all of these need to be done in order for support to officially be added to HA:
- Someone buys the thing
- Someone makes an issue here
- Someone figures out how to fix it
- Someone makes a PR
- PR needs to be looked at
- PR needs to be merged **We're currently here**
- python-broadlink new release
- Update HA requirements for new release, same PR process
- New HA release

**Comment by lordraiden** [comment]
> Just to say this again, all of these need to be done in order for support to officially be added to HA:
> 
>     * Someone buys the thing
> 
>     * Someone makes an issue here
> 
>     * Someone figures out how to fix it
> 
>     * Someone makes a PR
> 
>     * PR needs to be looked at
> 
>     * PR needs to be merged **We're currently here**
> 
>     * python-broadlink new release
> 
>     * Update HA requirements for new release, same PR process
> 
>     * New HA release

Isn't this already on HA PR process?
https://github.com/home-assistant/core/pull/45394

**Comment by KTibow** [comment]
Yes, it's a PR for the latest release, however the latest release doesn't exist yet.

**Comment by FlexxFR** [comment]
> If you want all patches together you can use the master branch.

How can I do that?

`ssh USER@IPADDRESS
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps`

This went succesfull but not fixing my issue yet.
I'm searching for the support of SP4L-EU (with different device type/code ) wich I see is present in the master branch.
0x618B: (sp4b, "SP4L-EU", "Broadlink"),

**Comment by yfands** [comment]
Goodday,

Totally confused here, I tried to add my Broadlink RM 3 mini, Home assistant replies with     "Unsupported device: 0x6508"
While in november last year it said: Unsupported device 0x653C  (see earlier comments) and no no other Broadlink devices here, only a green RM 3 mini...


Help...

Regards
Frank


________________________________
Van: FlexxFR <notifications@github.com>
Verzonden: zaterdag 13 februari 2021 13:51 uur
Aan: mjg59/python-broadlink <python-broadlink@noreply.github.com>
CC: yfands <yfands@live.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mjg59/python-broadlink] Add support for Broadlink RM4 pro (0x653C) (#472)


If you want all patches together you can use the master branch.

How can I do that?

ssh USER@IPADDRESS docker exec -it homeassistant /bin/bash pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps

This went succesfull but not fixing my issue yet.
I'm searching for the support of SP4L-EU (with different device type/code ) wich I see is present in the master branch.
0x618B: (sp4b, "SP4L-EU", "Broadlink"),

**Comment by lordraiden** [comment]
> 
> 
> Hi @kaskagorry. If you want to patch your installation before the release:
> 
>     1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 
>     2. Disable Protection mode
> 
>     3. Connect to the device via SSH and install the patch:
> 
> 
> ```
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
> ```
> 
>     1. Restart the server.

If I do this I will lose the changes if HA docker is updated, right? what is the latest patch currently?

**Comment by steelincable** [comment]
Just FYI for others: I just upgraded to 2021.2.3 and the latest OS update and my Broadlink stopped working (as expected).  Deleting my Broadlink integration, rerunning the steps by @felipediel, restarting HA and rerunning the Broadlink integration using the same device name as got things working again.  Note I tried running the integration prior to restarting HA and it threw a device unsupported error.  I didn't have to do anything other than the steps above.

**Comment by tyjtyj** [comment]
it wont merge into HA because python 3.8 and 3.9 not supported for python broadlink.

**Comment by lordraiden** [comment]
> it wont merge into HA because python 3.8 and 3.9 not supported for python broadlink.

@felipediel please, can this be fixed so it will be available to everyone in HA?

**Comment by lordraiden** [comment]
> Just FYI for others: I just upgraded to 2021.2.3 and the latest OS update and my Broadlink stopped working (as expected). Deleting my Broadlink integration, rerunning the steps by @felipediel, restarting HA and rerunning the Broadlink integration using the same device name got things working again. Note I tried running the integration prior to restarting HA and it threw a device unsupported error. I didn't have to do anything other than the steps above.

Which patch version did you use? 
pip3 install git+https://github.com/felipediel/python-broadlink.git@**patch-23** --force-reinstall --no-deps

**Comment by felipediel** [comment]
@tyjtyj Hi. As far as I know, Python 3.9 is supported. Did you find any problem?

@lordraiden This is the best I can offer you for now:

1. Open Home Assistant and install "SSH & Web Terminal" add-on
2. Disable Protection mode
3. Connect to the device via SSH and install the patch:
```
ssh USER@IPADDRESS
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
```
4. Restart Home Assistant.

You need to re-patch your installation every time you update Home Assistant.

**Comment by FlexxFR** [comment]
> @tyjtyj Hi. As far as I know, Python 3.8 and 3.9 are supported. Did you find any problem?
> 
> @lordraiden This is the best I can offer you for now:
> 
> 1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 2. Disable Protection mode
> 3. Connect to the device via SSH and install the patch:
> 
> ```
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
> ```
> 
> 1. Restart Home Assistant.
> 
> You need to re-patch your installation every time you update Home Assistant.

Thanks, at least this makes it work!

Are there any plans, steps, whatever, to make this part of HA Core?

**Comment by KTibow** [comment]
> Are there any plans, steps, whatever, to make this part of HA Core?

First, @mjg59 needs to release to PyPi.

**Comment by EvgenPavlyuchek** [comment]
thx
i can add rm4 pro after 
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
but
i dont see sensors temperature and humidity

**Comment by felipediel** [comment]
RM4 pro has no built-in sensors, you need the HTS2 cable.

**Comment by tyjtyj** [comment]
> 
> 
> @tyjtyj Hi. As far as I know, Python 3.8 and 3.9 are supported. Did you find any problem?
> 
> @lordraiden This is the best I can offer you for now:
> 
>     1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 
>     2. Disable Protection mode
> 
>     3. Connect to the device via SSH and install the patch:
> 
> 
> ```
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
> ```
> 
>     1. Restart Home Assistant.
> 
> 
> You need to re-patch your installation every time you update Home Assistant.

Cant merge with HA cause it's not release to pypi. @mjg59 

https://github.com/home-assistant/core/pull/45394

image

**Comment by kylemd** [comment]
> Cant merge with HA cause it's not release to pypi. @mjg59

There hasn't been a release yet, and 17.0 which is coming soon will be the first one to release to PyPi AFAIK

**Comment by bergetun** [comment]
Thank you for the work around.    Ill just skip HA updates until this is fixed in main version.

**Comment by felipediel** [comment]
You're welcome! It won't take long,

**Comment by bergetun** [comment]
> You're welcome! It won't take long,

Hope not  :) 
PS. I had to use the "33 patch" to get the two RM4 Mini to work..

**Comment by felipediel** [comment]
This branch has all the patches together:
```
pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
```

**Comment by xblackedemonx** [comment]
I don't use Docker. How can I install this?

**Comment by felipediel** [comment]
Which installation method did you choose?

If you are running HassOS, [this](https://github.com/mjg59/python-broadlink/pull/472#issuecomment-784153691) will set you up.
If you are running on a Python venv, activate the virtual environment and install the patch:
```
source venv/bin/activate
pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps
```

**Comment by xblackedemonx** [comment]
I installed it on the microSD using the Pi 4 image and Balena Etcher.

**Comment by felipediel** [comment]
Check if you have a Supervisor button on the sidebar. If so, click the button, go to the add-ons store and perform the first procedure. If not, do it the second way. If you don't feel safe doing this, waiting a while won't hurt. v0.17.0 is already merged into the dev branch, we're almost there.

**Comment by xblackedemonx** [comment]
Thank you very much for taking the time to reply.

Have a great day!

**Comment by felipediel** [comment]
You're welcome!

**Comment by luigipius** [comment]
hi @felipediel, how I can do to install the 0.17.0? 
when I try with:
`pip3 install git+https://github.com/felipediel/python-broadlink.git --force-reinstall --no-deps`
I receive "Successfully installed broadlink-0.16.0"

**Comment by felipediel** [comment]
You shouldn't install v.17.0 directly, it comes with several breaking changes.

**Comment by greghesp** [comment]
Hey @felipediel 

I've tried [this](https://github.com/mjg59/python-broadlink/pull/472#issuecomment-784153691) twice now.  It looks like its successfully installed:

image

but discover still fails 

image

Any ideas?

**Comment by felipediel** [comment]
Those instructions are for the Broadlink Integration (Home Assistant). Looks like you are using something different. You need to find out where the library is installed and patch it correctly.

**Comment by greghesp** [comment]
> Those instructions are for the Broadlink Integration (Home Assistant). Looks like you are using something different. You need to find out where the library is installed and patch it correctly.

Im using Home Assistant and Node-Red with `node-red-contrib-broadlink-control`

**Comment by felipediel** [comment]
node-red-contrib-broadlink-control doesnt't depend on this module. The patch will not work.

**Comment by KTibow** [comment]
Raise an issue over there, as the message says.

**Comment by dum-skywalker** [comment]
> Check if you have a Supervisor button on the sidebar. If so, click the button, go to the add-ons store and perform the first procedure. If not, do it the second way. If you don't feel safe doing this, waiting a while won't hurt. v0.17.0 is already merged into the dev branch, we're almost there.

I have the supervisor version as installation mode, nevertheles I can't disable the Protection mode on the config. any advice? I have the problem with "Unsupported device: 0x653c" for a Broadlink RM4pro
Thanks in advance.

**Comment by palbent** [comment]
Hi @felipediel 
I guess I'm doing something wrong. I'm trying to install my new RM4 pro (firmware v52079), I started to manually add the line `0x653C: (rm4, "RM4 pro", "Broadlink")` to the `__init__.py` file. After restarting, my HA didn't restart or even start correctly, so after checking I have seen that I got an error on the log file and reverted the change (removed the line).
Then I tried to install the line `pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps`. I wrote this directlz into the TERMINAL.
inst_broadlink|690x203

As you can see on the picture, the terminal says it was correctly installed, but when I try to integrate again the RM4pro I'm still getting that the device isn't supported.

Can you help me understanding what I'm doing wrong?

Many thanks

**Comment by felipediel** [comment]
This will set you up: https://github.com/mjg59/python-broadlink/pull/472#issuecomment-784153691. Don't skip any step.

**Comment by Heijt771** [comment]
Hi Felipe,

Thanks a lot for all the help you are giving in this thread.
Unfortunately just like palbent above I am also still unable to get the RM4 Pro running with hassio.
I am running the set up through a pi4, and used SSH to get into the pi, i ran the line which you suggested in #472 (comment) as well as all the other lines that were suggested in the different threads.

But still, I get the unknown device error.

I did try to install the broadlink component including the dependencies, however, then I seem to run into an error with updating cryptography.  Not sure if this is related somehow.

Do you maybe have any other ideas how I could get the RM4 Pro addedto my home assistant?

Cheers!!

**Comment by felipediel** [comment]
HI @Heijt771. Thank you!

Did you install the "SSH and Web Terminal" add-on? Did you access the container shell before installing the patch? This is important: `docker exec -it homeassistant /bin/bash`.

I have nothing to add to those instructions. The only thing I can emphasize is not skipping any step.

**Comment by Madelinot** [comment]
Yes, make sure you used the right SSH client.  That was my problem initially and I could not figure out why it would not work, until I read and followed the instructions EXACTLY.

**Comment by palbent** [comment]
Thanks you all.... I'm using the SSH&Webterminal. I did the procedure but it didn't work for me for any reason that I don't know.... but today I was able to manually add the line to the ini.py and probably an issue with the C instead c.... but it's working now.

Thanks again for zour attention and support.

**Comment by felipediel** [comment]
Hello everybody. The update is finally released. The patch is no longer necessary, you just need to update Home Assistant.

**Comment by xblackedemonx** [comment]
Amazing news! Thank you so much

**Comment by felipediel** [comment]
You're welcome!

**Comment by oferbar** [comment]
Hi,
I'm running the HA OS and just got the latest updates for Apr 10, 2021:
* core-2021.4.3
* supervisor-2021.03.9
* Home Assistant OS 5.13
* 
Still, when I try to add both Broadlink devices (mini, Pro) I get a failure error' like:

2021-04-11 00:55:53 ERROR (MainThread) [homeassistant.components.broadlink.config_flow] Failed to connect to the device at 192.168.X,Y: Device not found

Did I miss anything?

Thanks

**Comment by felipediel** [comment]
The IP addreses are wrong or you are not connected to the same network.

**Comment by msreef** [comment]
If anyone is stuck on this like I was, if you have set up the Broadlink in your phone's app, be sure to switch off 'Lock Device'. That was stopping Home Assistant from being able to connect to it via IP address.

**Comment by M2ar10** [comment]
I just have a new broadlink RM4 pro and have the latest version of ha running on my synology (docker). And i still have the issue device not suported ... Help pleas :(

**Comment by sevagjb** [comment]
The problem
i bot new Broadlink RM4 pro , its not supported can you help ???
when i add the Integration i receive this message:
Aborted
Device not supported,
This is device datils:
Device info : S/N code
PID ; 00000000000000000000000013520000
DID : 00000000000000000000ecObae6edc02
loT Cloud : World
MAC: XX:XX:XX:XX:XX:XX
Firmware :
V62092
Device IP : 192.168.1.60@80
Data Cloud : European server
SDK : 2.17
Plug-in version : 1.6.7.2
Routine traits : Trigger
Connector Type: ‎Wi-Fi, Radio Frequency
ASIN: ‎B083LLLVPN

can i fix it??
Thanks

**Comment by palbent** [comment]
Hi
Did you tested to introduce manually this code? It worked in previous versions
Regards

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
