### PR TITLE
Add support for RM4 mini (0x648d)

### PR DESCRIPTION
**Pull request by felipediel**
## Proposed changes
Add support for [RM4 mini (0x648d)](https://github.com/mjg59/python-broadlink/issues/377#issuecomment-680686996).

### CODE REVIEW

**Review by Danielhiversen — APPROVED** [review]

**Comment by felipediel** [comment]
Thank you!

**Comment by trireme32** [comment]
@felipediel Do you know when we can expect this version to be released into the wild?

**Comment by felipediel** [comment]
0.116 probably.

**Comment by jorgeMAbreu** [comment]
I'm running Home Assistant 0.117.6 and still facing this issue. Any ideas?

**Comment by felipediel** [comment]
This device is already supported. I think something is preventing you from getting the updates. Are you using custom components? (e.g. Floureon)

**Comment by jorgeMAbreu** [comment]
I'm pretty new to HASS... I just have some Shellys(forHass) and Sonoffs. Nothing more.

**Comment by jorgeMAbreu** [comment]
Further information:

Log Details (ERROR)
Logger: homeassistant.components.broadlink.config_flow
Source: components/broadlink/config_flow.py:48
Integration: Broadlink (documentation, issues)
First occurred: 19:15:35 (5 occurrences)
Last logged: 19:51:19

Unsupported device: 0x6539. If it worked before, please open an issue at https://github.com/home-assistant/core/issues

**Comment by felipediel** [comment]
Please check the error message in the logs. I see is only two possibilities:
1. Your device is not 0x648d. In this case you need to tell me your device type so I can add it.
2. There is an error in your installation and you don't have broadlink>=0.15.

**Comment by felipediel** [comment]
Perfect timing, I sent the message at the same time hahah. Ok, it was 1, I will add your type.

**Comment by felipediel** [comment]
I created the PR. Now we just need to wait.

**Comment by jorgeMAbreu** [comment]
Thank you very much for your quickest support! Let's wait then.

**Pull request merged**
