### PR TITLE
Fix inaccurate hysen temperature

### PR DESCRIPTION
**Pull request by fustom**
## Context

Hysen heating thermostat returned inaccurate temperature.

## Proposed change

Hysen payload[17] first half contains the the missing bits.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New device
- [ ] New product id (the device is already supported with a different id)
- [ ] New feature (which adds functionality to an existing device)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Additional information

- This PR fixes issue: fixes #https://github.com/mjg59/python-broadlink/issues/678
- This PR is related to: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] The code has been formatted using Black.
- [x] The code follows the [Zen of Python](https://www.python.org/dev/peps/pep-0020/).
- [x] I am creating the Pull Request against the correct branch.
- [ ] Documentation added/updated.

### CODE REVIEW

**Review by rjulius23 — APPROVED** [review]
LGTM

**Comment by rjulius23** [comment]
@felipediel is it possible to get this to the latest release ?

**Comment by felipediel** [comment]
It may take a while for the next release, I'm swamped with work and no free time to work on this integration.

This code would also need a clean up and rebase, as it is incompatible with the current version of the dev branch. If the author doesn't know how to do it, I can help as soon as I have time.

Thanks for the contribution anyway, this is certainly something we want to add.

**Comment by rjulius23** [comment]
Can this be released ?

**Comment by felipediel** [comment]
Don't worry, I will merge it before the next release, I just don't have time for the whole release process right now, I will be back when I do

**Comment by rjulius23** [comment]
Can I help with the release process ? Is there a guide ?

**Comment by fustom** [comment]
Happy 1st year anniversary.

**Comment by rjulius23** [comment]
How can we push this to release ?

**Comment by felipediel** [comment]
Sorry, I am on a rush, I cannot change focus right now. To create a new release we need to analyze all breaking changes we've made since the last version and submit a PR to Home Assistant in order to keep it up to date.

I feel that I'm not giving enough attention to this project, but I just can't, my job is demanding everything I have. Maybe we need more people to help with updates, if anyone is interested ping mjg.

*Be aware that it takes some spare time and responsibility, this project has thousands of active users and if something breaks it needs to be fixed immediately.

**Comment by rjulius23** [comment]
Hey @mjg59,

I can have some spare time to help out with some tasks. Can you link me a guid or tasks that I can do to help ?

cheers,
Gyula

**Comment by sancyx** [comment]
It seems to me that this PR addresses the same problem as this: https://github.com/mjg59/python-broadlink/pull/720.
Actually it seems a bit more accurate. I'm newbie in HASS and actually using Computherm E series thermostats with https://github.com/algirdasc/hass-floureon which is based on broadIink module. So not sure how can I help but would also love this to be fixed.

**Comment by felipediel** [comment]
Thank you @fustom! I believe that https://github.com/mjg59/python-broadlink/pull/772 has fixed the problem. If not, please reopen this PR.

**Comment by fustom** [comment]
Yeah #772 also works. I don't mind.

**Pull request closed without merging**
