### PR TITLE
Add in AP Mode device setup for new Broadlink devices.

### PR DESCRIPTION
**Pull request by walkention**
I have added in the ability to setup a new Broadlink device on a local wireless by putting it into AP Mode, connecting to the BroadlinkProv WiFi network, and using the setup() function. 

I have only tested this with the Broadlink RM3 Mini device.

### CODE REVIEW

**Comment by vicfergar** [comment]
Great work! :)

**Comment by johado** [comment]
Very nice! Got it to work om my Raspberry pi 3 for an SP2 device after adding support for specifying the local IP to bind to (Took the code from the discover() function).
One odd thing I noticed is that the name of the device reported when doing discovery looks weird.

**Comment by johado** [comment]
Another thing I noticed is that for the device provisioned with this way, the auth key is all zeroes.
Everything seems to work anyway though.

**Comment by walkention** [comment]
@johado ,

What IP address did you have to bind to? I noticed that my RM3 sets itself as 192.168.10.1 in AP mode but it still was able to be provisioned by sending a broadcast packet to 255.255.255.255.

Hmm that's weird about the device name and auth key. Let me run some tests and see I get the same results with the two RM3's I have.

Thanks for testing that!

**Comment by johado** [comment]
I normally have the Rpi3 in AP mode on wlan0 using hostapd and fixed IP 192.168.1.1 and runing a DHCP server.  No routing to eth0 so the WLAN used for the plugs is isolated and I can run wireshark on the pi. When provisioning I kill hostapd and run ifconfg wlan0 up and iw wlan0 connect BroadlinkProv (IIRC) so the IP is still 192.168.1.1 which I have to specifying to setup(). Eth0 gets a 192.168.0.x adress from my home router.
I believe I have pushed my changes to my fork.

The default name in chineese is probably what to expect, but the auth key and the wrong time can probably be fixed if it's related to the provisioning.
Do you have a tool that can parse and decrypt saved package from wireshark?

**Comment by appden** [comment]
It would be really nice to see this merged and part of the next official release. It worked great for me.

**Comment by mjg59** [comment]
Thank you!

**Pull request merged**
