### PR TITLE
fix encryption errors

### PR DESCRIPTION
**Pull request by ajuniper**
These fixes address the issues seen in issue #294 
I'm not a Python expert so they might be solid in all environments but they work for me...

### CODE REVIEW

**Comment by charliejllewellyn** [comment]
Nice thanks for this fix, it worked for me :) There is an error on line 170 though where you have an extra "("

return encryptor.update((bytes(payload)) + encryptor.finalize() should be
return encryptor.update(bytes(payload)) + encryptor.finalize()

Hopefully someone merges this soon :)

**Comment by felipediel** [comment]
HI @ajuniper. It seems that this problem still exists. Could you please resolve the conflicts so we can merge?

**Comment by felipediel** [comment]
I resolved conflicts and merged. Thank you very much @ajuniper!

**Comment by ajuniper** [comment]
@felipediel Apologies for not commenting sooner, been AFK.  Glad you resolved the conflicts.

**Pull request closed without merging**
