### PR TITLE
Raise exceptions for errors

### PR DESCRIPTION
**Pull request by felipediel**
## The problem
Things are failing silently. When we send a request and an error occurs, the device sends an error code in the response. This is valuable information for dealing with the problem. But this is being ignored in the current implementation. Errors are passing by without leaving clues.

Let's take a practical example. We need authorization to send a command. If we send a command without being authorized we will receive an authorization error (0xfff9) in the response. It's simple to deal with this error, we just need to re-authenticate and send the command again. But it is currently not possible to catch this error, so we cannot deal with it.

Here is a [real case](https://github.com/home-assistant/core/issues/32313#issuecomment-620905430). Once @AndroVet's device closes the connection for some reason, the device object breaks silently (because it doesn't know it has been logged out). @AndroVet is being logged out due to the large number of connections, probably. We are not detecting this error and his switches are failing silently. We should inform the integrations when an error occurs so they can deal with it.

## Proposed changes
My suggestion is to raise an exception whenever the device informs an error. In this way, integrations will have material to decide how to respond. I found the error codes in the [official documentation](https://docs.ibroadlink.com/public/appsdk_en/appsdk_09/). I compared some with error codes that I captured in a controlled environment. They match.

These are the changes I propose:
- Create a separate file called exceptions.py to keep thing organized.
- Create a common base class for all Broadlink exceptions.
- Create a Broadlink exception for each type of error.
- Create a dictionary that maps error codes to exceptions.
- Create a helper function to serve as an interface for this dictionary.
- Create a function that checks for errors and raises the Broadlink exception corresponding to the error found.
- Use this function to check all responses received from the device.

## Breaking changes
These are breaking changes because we are gonna start raising exceptions, we will no longer fail silently as before. Some minor changes will be needed in the integrations. I commit to bringing these changes to Home Assistant.

### CODE REVIEW

**Comment by felipediel** [comment]
@Danielhiversen @mjg59 What do you think about this?

**Comment by felipediel** [comment]
I will move to draft until I make fine adjustments in Home Assistant. But you can review the code anyway, since I don't intend to change it anymore.

**Comment by mjg59** [comment]
This looks extremely good to me.

**Comment by Danielhiversen** [comment]
Is it still a draft?

**Comment by felipediel** [comment]
@Danielhiversen This code is ready, but we still have to update Home Assistant to handle these exceptions. I'm gonna mark it as ready and work on the updates tonight.

**Comment by felipediel** [comment]
I am implementing these exceptions in Home Assistatnt, but I am getting a ReadError every time I try to learn a new code. I think we always got this error and we didn't know. I'll investigate. I will move this PR to draft again because it is dangerous and cannot be merged yet.

**Comment by felipediel** [comment]
I already found the problem. I just fixed it. I think that tomorrow everything will be ready.

**Comment by felipediel** [comment]
Here we go.

**Pull request merged**
