### PR TITLE
0.16.1

### PR DESCRIPTION
**Pull request by felipediel**
### Clean up
- Add GT Actions (https://github.com/mjg59/python-broadlink/pull/470)
- Run black (https://github.com/mjg59/python-broadlink/pull/470)
- Clean up get_energy() (https://github.com/mjg59/python-broadlink/pull/471 https://github.com/mjg59/python-broadlink/pull/504)
- Fix MP1's check_power_raw annotation (https://github.com/mjg59/python-broadlink/pull/485)
- Use context manager for connection (https://github.com/mjg59/python-broadlink/pull/464)

### Bug fixes
- Clamp the packet count between 0x8000 and 0xFFFF (https://github.com/mjg59/python-broadlink/pull/486)
- Improve RM4 communication (https://github.com/mjg59/python-broadlink/pull/490)
- Allow negative temperatures (https://github.com/mjg59/python-broadlink/pull/502)
- Timeout improvements (https://github.com/mjg59/python-broadlink/pull/464 https://github.com/mjg59/python-broadlink/pull/506)
- Filter unsupported features and convert sensor data to float (https://github.com/mjg59/python-broadlink/pull/495)
- Fix encryption errors (https://github.com/mjg59/python-broadlink/pull/505)

### New product ids
- Broadlink RM4C mini (0x6539) (https://github.com/mjg59/python-broadlink/pull/476)
- Broadlink RM4 pro (0x653C) (https://github.com/mjg59/python-broadlink/pull/472)
- Broadlink RM4S (0x6364) (https://github.com/mjg59/python-broadlink/pull/475)
- Broadlink MCB1 (0x756F) (https://github.com/mjg59/python-broadlink/pull/478)
- Broadlink MCB1 (0xA56A) (https://github.com/mjg59/python-broadlink/pull/478)
- Broadlink RM mini 3 (0x6508) (https://github.com/mjg59/python-broadlink/pull/479)
- Efergy Ego (0x271D) (https://github.com/mjg59/python-broadlink/pull/481)
- Broadlink SCB1E (0x5115) (https://github.com/mjg59/python-broadlink/pull/514)
- Broadlink SCB1E (0x6113) (https://github.com/mjg59/python-broadlink/pull/488)
- Broadlink SP4L-EU (0x618B) (https://github.com/mjg59/python-broadlink/pull/489)
- Broadlink SP4L-UK (0xA589) (https://github.com/mjg59/python-broadlink/pull/491)
- Broadlink RM3 mini (0x27d3) (https://github.com/mjg59/python-broadlink/pull/493)
- Broadlink SP4L-AU (0x6489) (https://github.com/mjg59/python-broadlink/pull/498)
- BG Electrical AHC/U-01 (0x51E2) (https://github.com/mjg59/python-broadlink/pull/497)
- Broadlink MCB1 (0x6111) (https://github.com/mjg59/python-broadlink/pull/509)

### CODE REVIEW

**Comment by guieiras** [comment]
Very happy for this release! Congrats

**Comment by felipediel** [comment]
@mjg59 @Danielhiversen Hi. I cleaned up the commit history a little bit: https://github.com/felipediel/python-broadlink/commits/test. Do you mind if I force push that branch to master?

And then could we have a release?

**Comment by felipediel** [comment]
I reverted the 0.16.1 tag to avoid problems while we don't have a release on PyPi.

**Comment by xblackedemonx** [comment]
Thanks a lot for this! I cannot wait for the RM4 Pro support!

**Comment by ofirshtrull** [comment]
@felipediel when will this new version  0.16.1 will be upgraded in pypy?

**Comment by felipediel** [comment]
I don't know. I don't have access to PyPi, but if you want my opinion, I think we should go straight to 0.17.0, the version I'm working on right now. It will be ready in a week and it is much better.

**Comment by ofirshtrull** [comment]
who says after 0.17.0 is ready it will be also pushed ;-)

**Comment by felipediel** [comment]
Not me, I don't have the password, but I'll finish it if you don't mind, batman.

**Comment by KTibow** [comment]
There is a way to configure GitHub Actions to auto-publish releases to PyPi, when a new GitHub release is published. It involves the maintainer generating an API key, and then putting it in the secrets tab of settings.

**Pull request merged**
