### PR TITLE
Add new device support: Broadlink MP1 Smart power strip

### PR DESCRIPTION
**Pull request by vicfergar**
Hi mjg59,

I'm using your library to control my Broadlink devices and I've include a new device. Hope you want include this. 👍

### CODE REVIEW

**Comment by mjg59** [comment]
Nice work! I'll review this over the next few days and then merge it.

**Comment by vicfergar** [comment]
Great! All remarks are welcome!

**Comment by dixnor** [comment]
Hi,
Tried this fork and having issues checking power status of the mp1 strip. Seems problem coming from bitwise & and boolean conversion. When I check the power status, I get this error

device.check_power()
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.2-py2.7.egg/broadlink/__init__.py", line 296, in check_power
    data['s1'] = bool(state & 0x01)
TypeError: unsupported operand type(s) for &: 'str' and 'int'
The socket power switch works fine.

**Comment by vicfergar** [comment]
Hi dixor,

Looks like a python version incompatibility problem. I had it working on python 3.

Try with a casting to int for state: 
state = int(payload[0x0e])

Hope it helps!

**Comment by dixnor** [comment]
HI vicefergar,
Yes It has something to do with Python version. Anyway cant run Python 3.0 in my case and have to stick 2.7. Tried your suggestion and having now another error:
invalid literal for int() with base 10: '\x0f'
But I think for any reason that the payload result is seen as a string value.

**Comment by Oliv3rDog** [comment]
Is there any way to add support for TC2 devices (Broadlink Wall Switches)?
By the way, great work!!!

**Comment by vicfergar** [comment]
Hi Oliv3rDog, 
Sure it can be included. I dont have any of those devices but should be easy to include having one and sniffing comunication with Android app.

**Comment by vicfergar** [comment]
@mjg59 Any advance about this PR? I'm waiting to include this device in other platform using the library 😄 Regards!

**Comment by mjg59** [comment]
Hi,

It'll need to be fixed up to work with Python 2 before merging - I'm out of town right now but will probably be in a position to look at it in more detail next week, but if you can figure it out I can merge.

**Comment by vicfergar** [comment]
Ok I have fixed it to get it working with python2 too 😉

**Comment by vicfergar** [comment]
I have replicated the strategy from check_sensors method in a1 class to allow compatibility with both python versions

**Comment by Oliv3rDog** [comment]
Thanks Vicfergar. I asked that because I am still looking for a in wall switch that keeps the manual controlling and informs its status to any connected controller (using Home Assistsnt) and with this library I have already got working A1, RMpro, RMmini and SPmini...
With the TC2 integration, I could through out all my dangerous Arduino DIY stuff... 😄

**Comment by dixnor** [comment]
Hi Vicfergar
your mod works for Python2
Connecting to Broadlink device....
Connected....
1
{'s3': True, 's2': True, 's1': True, 's4': True}
Thanks

**Comment by mjg59** [comment]
Merged, thanks!

**Pull request closed without merging**
