### PR TITLE
check_power_raw included for mp1 devices

### PR DESCRIPTION
**Pull request by vicfergar**
New method included for raw format state reading in MP1 devices

### CODE REVIEW

**Comment by mjg59** [comment]
Thanks!

**Comment by hamwong** [comment]
Hi @vicfergar 

I believe check_power_raw() is not reading right value,
in fact app of Honyar providing realtime voltage:225.9v, current:0.0318A, and Power 1.88W
it also provide today power usage:0.33kWh and total usage since starting:469.39kWh

**Comment by vicfergar** [comment]
Hi @hamwong

I don't understand, the Broadlink MP1 has no power monitor feature. check_power_raw() read the switch state of each socket (on/off). Which power strip model are you using?

**Comment by hamwong** [comment]
I am using MP1 and I have real time power monitor meter,
my dev_type 0x4ef7, I believei it's Honyar OEM. I am using the app of Honyar to control/read power strip real time status,

This is the power strip interface
<a href="https://ibb.co/xYPVnfS"></a> 

This is the power strip interface with power measurement
<a href="https://ibb.co/X2wBTcp"></a> 

This is the power useage hourly report (under daily)
<a href="https://ibb.co/7kqCFLp"></a> 

This is the power useage daily report (under month)
<a href="https://ibb.co/Lkry5cg"></a>

**Comment by hamwong** [comment]
I do a bit further test, I simulate my MP1 as SP2
and I can get current power usage reading and I think return value is correct,
but it won't return power voltage and power current value, I don't know it was due to SP2 don't have such function or starting programmer think these value not important as I don't have SP2 to verify.

import broadlink
devices = broadlink.sp2(devtype=("sp2"), host=("192.168.1.1",80), mac=bytearray.fromhex("xxxxxxxxxxxx"))
devices.auth()
True
devices.get_energy()
1.8900000000000001

I really not a programmer, I just tried to copy energy block from SP2 to MP1 but it doesn't work,

```
 	    def get_energy(self):
	        packet = bytearray([8, 0, 254, 1, 5, 1, 0, 0, 0, 45])
	        response = self.send_packet(0x6a, packet)
	        err = response[0x22] | (response[0x23] << 8)
	        if err != 0:
	            return None
	        payload = self.decrypt(bytes(response[0x38:]))
	        if isinstance(payload[0x7], int):
	            energy = int(hex(payload[0x07] * 256 + payload[0x06])[2:]) + int(hex(payload[0x05])[2:]) / 100.0
	        else:
	            energy = int(hex(ord(payload[0x07]) * 256 + ord(payload[0x06]))[2:]) + int(
	                hex(ord(payload[0x05]))[2:]) / 100.0
	        return energy
```

result still as
```>>> devices.get_energy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'mp1' object has no attribute 'get_energy'```

**Comment by hamwong** [comment]
Hi @vicfergar

did you try that your MP1 have power monitor feature or not?

**Comment by hamwong** [comment]
I realize I was modify wrong file, I modify the file for python 2.8, after modify the file for python3, I able to read energy now,

Strip Status: {'s4': True, 's2': True, 's3': True, 's1': True}
Strip Status Raw: 15
Energy Usage: 1.94W

**Pull request merged**
