### PR TITLE
sp2.get_energy

### PR DESCRIPTION
**Pull request by eschava**
Get current used energy in Watts

### CODE REVIEW

**Comment by kzoltaan** [comment]
I receive same bytes but something not...

**Comment by kzoltaan** [comment]
this is the answer
1 0 0 0 0 0 252 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 68 117 103 111 32 51 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 225 7 3 55 15 5 11 8 166 173 113 35 159 96 216 59

**Comment by eschava** [comment]
@kzoltaan sorry, it is an answer for what?

**Comment by kzoltaan** [comment]
"Does this code work with SP2? I send to SP2 the bytes [8, 0, 254, 1, 5, 1, 0, 0, 0, 45] and receive the same bytes [8, 0, 254, 1, 5, 1, 0, 0, 0, 45]. "

**Comment by snomile** [comment]
@VooDooN1  I tested the formula on my SP2 with a electric heater, and I think the result is good. There's a slight delay between E-Control's data and the data from formula, that's quite normal because E-Control server is in the cloud.

**Comment by mjg59** [comment]
Thanks! Merged the commit that wasn't in another PR.

**Pull request closed without merging**
