### PR TITLE
Add support for BG Electrical Smart Sockets

### LINKED ISSUE #289: New device (devtype 0x51e3)
Hi,
I have purchased this device:
https://www.bgelectrical.uk/smart-sockets

After a bit of digging, I found out that they use a broadlink chip:

https://community.home-assistant.io/t/uk-wifi-smart-socket-screwfix-testing/119995/5

So I tried connecting to broadlink-mqtt

Kind of works:
```
$ pi@piup:~/broadlink-mqtt $ python mqtt.py
[2019-10-09 10:27:40,822] DEBUG Connected to 'Unknown' Broadlink device at '192.168.0.99' (MAC c8:f7:42:fc:e5:45) and started listening for commands at MQTT topic having prefix 'broadlink/'
[2019-10-09 10:27:40,834] DEBUG Connected to MQTT broker, subscribing to topic broadlink/#
```

It connects, so there must be a way.
I have a spare device that I can send by post
I can also send debug logs or whatever is needed

also:
```python
>>> import broadlink
>>> print hex(broadlink.discover(timeout=10)[0].devtype)
0x51e3
```
How do I find out what commands it takes?
It could be compatible with an MP1 device but only 2 sockets
How do I add the devtype in the library and then test it locally?

Thanks

### PR DESCRIPTION
**Pull request by barnybug**
This adds support for these sockets which basically send json over the broadlink protocol:
https://www.bgelectrical.uk/smart-sockets

Fixes #289

### CODE REVIEW

**Comment by vzorglub** [comment]
Verified. This works

**Comment by barnybug** [comment]
Could we get this merged please?

**Comment by barnybug** [comment]
@mjg59 could we get this merged please?

**Comment by barnybug** [comment]
thanks!

**Comment by felipediel** [comment]
Hi @barnybug. Thank you for this!

Just out of curiosity... I see that this device has two slots, but the state supports three (pwr, pwr1 and pwr2). What does the pwr do?

**Comment by barnybug** [comment]
@felipediel it represent both sockets simultaneously if I recall correctly

**Comment by felipediel** [comment]
Thank you!

**Comment by cgorms** [comment]
@barnybug I had to re-install my Broadlink setup for BG1 sockets and noticed you've deleted the git for them... is there another work around?

This the install process I previously went through...
cd /srv
sudo git clone https://github.com/eschava/broadlink-mqtt.git
cd broadlink-mqtt
sudo pip3 install -r requirements.txt
sudo pip3 install git+https://github.com/barnybug/python-broadlink@add_bgelectrical_sockets

I'm now getting '**ERROR No Broadlink devices found**' this is evening if the timeout is extended and I use the direct connection option within mqqt.conf

Any advice or assistance would be greatly appreciated.

**Comment by KTibow** [comment]
@cjorms just clone from python-broadlink master.

**Comment by emberbrook** [comment]
I am just about to give up on mqtt control of my BG1 sockets. I just executed 
pi@raspberrypi:~/broadlink-mqtt $ sudo pip3 install git+https://github.com/barnybug/python-broadlink@add_bgelectrical_sockets --no-cache-dir

and got

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/barnybug/python-broadlink@add_bgelectrical_sockets
  Cloning https://github.com/barnybug/python-broadlink (to revision add_bgelectrical_sockets) to /tmp/pip-req-build-epiw9sck
  Did not find branch or tag 'add_bgelectrical_sockets', assuming revision or ref.
error: pathspec 'add_bgelectrical_sockets' did not match any file(s) known to git
Command "git checkout -q add_bgelectrical_sockets" failed with error code 1 in /tmp/pip-req-build-epiw9sck

I can omit  --no-cache-dir or use pip instead of pip3 and get the same result. I don't understand cloning or branching or much about Linux. Any fixes?

**Comment by felipediel** [comment]
Hi. This is a PR. Once it is merged, you should use the master branch:
```
pip3 install git+https://github.com/mjg59/python-broadlink
```

**Pull request merged**
