### PR TITLE
Add support for Broadlink SP4L-UK (0x7587)

### PR DESCRIPTION
**Pull request by joh90**
- Add new SP4L-UK type
- Switch: SP4 check power and nightlight to return as boolean …
  - Instead of int
  - Consistency with sp2's check_power
    - https://github.com/mjg59/python-broadlink/blob/master/broadlink/switch.py#L178

#### Adding new SP4L-UK
image

#### Checking power and nightlight state before and after turning them on
image

@felipediel

### CODE REVIEW

**Comment by felipediel** [comment]
What is the response to sp4.get_state()?

**Comment by joh90** [comment]
> What is the response to sp4.get_state()?

```In [7]: devices[0].get_state()
Out[7]: 
{'pwr': 0,
 'ntlight': 0,
 'indicator': 1,
 'usbpwr': 0,
 'maxworktime': 0,
 'usbmaxworktime': 0,
 'ntlbrightness': 100,
 'current': 0,
 'volt': -1,
 'power': 0,
 'totalconsum': -1,
 'overload': -1,
 'childlock': 0}```

**Comment by felipediel** [comment]
Awesome. Thank you!

**Comment by joh90** [comment]
thanks!

**Pull request merged**
