### PR TITLE
Add support for Broadlink RM mini 3 (0x6507)

### PR DESCRIPTION
**Pull request by felipediel**
Thank you @gurbyz!

closes https://github.com/mjg59/python-broadlink/issues/588

### CODE REVIEW

**Comment by rmoggia** [comment]
Hello. Did I get it right that error 0x6507 has been resolved? I have these versions:
 core-2021.8.7, supervisor-2021.06.8, Home Assistant OS 6.2.
What should I do if the problem has been solved?
Thanks

**Comment by gurbyz** [comment]
I didn't try my Broadlink RM mini 3 0x6507 yet in HA, because I'm was waiting for my Airco first. But this evening I tried. And still got the Not supported error.

I'm not sure if HA already has this changes, because my PR made it to the dev branch here. I guess python-broadlink has to be released to master first. And then HA has to upgrade their dependency on python-broadlink. @felipediel Is there a release planned? Could you maybe release for @rmoggia and me?

**Comment by felipediel** [comment]
Hi @gurbyz, The next version still needs to be finished. I'll do it as soon as I find time. At the moment I have a lot of work, deadlines, I can't stop, I'm sorry.

**Comment by gurbyz** [comment]
Thx for the heads up. And no problem of course. Keep up the good work on your lib! Success with deadlines/work.

**Comment by rmoggia** [comment]
you need to add this line in the broadink engine file instead of the line: 0x6539 with 
0x6507 (rmminib,"RM mini 3","Broadlink");
immagine
But be careful that if you update the core you have to redo it.
I don't know how the change is consolidated otherwise I would do it myself. I hope I have helped you.
Obviously this is the procedure for those with HA in docker.
My broadlink is an orange R3Mini with a black hat.
Hi

**Pull request merged**
