### PR TITLE
Add support for (0x27cc) RM mini 3

### PR DESCRIPTION
**Pull request by sivero**
Add support for (0x27cc) RM mini 3

### CODE REVIEW

**Comment by felipediel** [comment]
Is this an OEM device?

**Comment by sivero** [comment]
I don’t  know actually. I imported them from China. I have a few RM mini 3 more but they have another IDs.
from the outside the devices they look pretty much the same but the packaging was blue in some of them and white on the others (don’t remember which one had the white packaging)
they used to work fine in Home Assistant before upgrading to 0.115

if you need more info about them let me know.

**Comment by felipediel** [comment]
I asked because it is only registered in IHC and the brand does not show up. But don't worry about this, it's more out of curiosity. Thanks for your contribution and I hope you can get your device up and running again soon. Sorry for the inconvenience, but things will get better now. After [this update](https://github.com/home-assistant/core/pull/39920) your device will be automatically discovered.

**Comment by sivero** [comment]
Thank you for your time! I really appreciate your work.

**Pull request merged**
