### PR TITLE
return devices

### PR DESCRIPTION
**Pull request by Danielhiversen**

### CODE REVIEW

**Comment by mjg59** [comment]
Can you provide a description for why you want this change?

**Comment by Danielhiversen** [comment]
This is a bug fix to make sure that the device list is returned otherwise None can be returned.

**Comment by mjg59** [comment]
Under what circumstances can you get None?

**Comment by Danielhiversen** [comment]
It will return None if you do not get a socket.timeout at line 117:
https://github.com/mjg59/python-broadlink/pull/26/files#diff-8651c630cb85a737f3c4c67091ea485fR117

**Comment by mjg59** [comment]
Why does that not put you through the loop again?

**Comment by Danielhiversen** [comment]
if (time.time() - starttime) > timeout

**Comment by mjg59** [comment]
Ok. So it's a race where if you get a response close enough to the timeout, you may exit the loop condition without returning anything? Could you edit the patch description to describe that failure just in case anybody ends up wondering what's going on there? Thanks!

**Comment by Danielhiversen** [comment]
Do you mean update the pr description?

**Comment by mjg59** [comment]
The commit message. I'm not able to edit it using the UI - I can fetch your branch and edit it locally, but it'd be easier if you just edit it and repush your branch.

**Comment by Danielhiversen** [comment]
You can change it from the ui
Push "Merge pull request", then you get a box where you can change the commit message before you press "confirm merge"

**Comment by mjg59** [comment]
That edits the merge commit message, not the description in the actual commit. The latter is what will show up if people do a git blame.

**Pull request closed without merging**
