### PR TITLE
Add support for Broadlink RM4 pro (0x649b)

### PR DESCRIPTION
**Pull request by felipediel**
And we have [another friend](https://github.com/home-assistant/core/issues/40191#issuecomment-694637097).

### CODE REVIEW

**Comment by haglen** [comment]
I got through adding my RM4 Pro through the new integration, but no entities/devices were created. I'm hoping this will fix the problem as I've got nothing right now.

**Comment by felipediel** [comment]
Yes, this will fix.

**Comment by haglen** [comment]
We’ve had a number of releases and this hasn’t made it in yet? I’ve lost support for half my home automation as a result.

**Comment by felipediel** [comment]
I opened the PR in the first hour. Not sure what else you want from me.

Use the remote for now, it's not the end of the world 🤣

**Comment by haglen** [comment]
Its the end of the first world!

**Comment by felipediel** [comment]
It's available on Home Assistant 0.116.0b2.

**Pull request merged**
